### PR TITLE
Fix marshalling of relationships for several entities

### PR DESCRIPTION
**Pull request by jamesfcarter**

### CODE REVIEW

**Review by matthew1809 — COMMENTED** [review]
Does the relationships struct allow custom flow data relationships to be returned in it?

**Comment by jamesfcarter** [comment]
> Does the relationships struct allow custom flow data relationships to be returned in it?

Ach! No. Didn't consider that (is it in the docs?)

**Comment by matthew1809** [comment]
> > Does the relationships struct allow custom flow data relationships to be returned in it?
> 
> Ach! No. Didn't consider that (is it in the docs?)

Good question, I think no! Need to fix that! You'll see it happening in the guides: https://www.moltin.com/developer/guides/create-related-products-with-flows

Essentially if you create an [entry relationship](https://docs.moltin.com/api/advanced/custom-data/entry-relationships) from a product to another flow entry, that flow entry ID will be returned in the relationships of the product.

This also applies to includes. For example if you created a wishlists flow, and created a relationship from a product to a wishlist, you would be able to call GET /product/:ID?include=wishlists

**Review by matthew1809 — COMMENTED** [review]
Nice! Includes might be harder because we don't know the structure of what will be included unless they are core entities, so maybe included will have to take the same approach as you do for flow data on core entities?

**Comment by jamesfcarter** [comment]
> Nice! Includes might be harder because we don't know the structure of what will be included unless they are core entities, so maybe included will have to take the same approach as you do for flow data on core entities?

Yeah - not really thought about includes yet. Future work!

**Review by matthew1809 — APPROVED** [review]
LGTM!

**Pull request merged**
